# Generated by Django 3.1.1 on 2022-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='day',
            field=models.CharField(choices=[('monday_odd', 'Monday Odd Menu 1'), ('tuesday_odd', 'Tuesday Odd Menu 1'), ('wednesday_odd', 'Wednesday Odd Menu 1'), ('thursday_odd', 'Thursday Odd Menu 1'), ('friday_odd', 'Friday Odd Menu 1'), ('monday_even', 'Monday Even Menu 2'), ('tuesday_even', 'Tuesday Even Menu 2'), ('wednesday_even', 'Wednesday Even Menu 2'), ('thursday_even', 'Thursday Even Menu 2'), ('friday_even', 'Friday Even Menu 2'), ('unspecified', 'Unspecified')], default='unspecified', max_length=100, verbose_name='Chosen Day'),
        ),
    ]
