# Generated by Django 3.1.1 on 2022-09-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='celery',
            field=models.BooleanField(default=False, verbose_name='Celery'),
        ),
        migrations.AddField(
            model_name='menu',
            name='crustaceans',
            field=models.BooleanField(default=False, verbose_name='Crustaceans'),
        ),
        migrations.AddField(
            model_name='menu',
            name='eggs',
            field=models.BooleanField(default=False, verbose_name='Eggs'),
        ),
        migrations.AddField(
            model_name='menu',
            name='fish',
            field=models.BooleanField(default=False, verbose_name='Fish'),
        ),
        migrations.AddField(
            model_name='menu',
            name='lupin',
            field=models.BooleanField(default=False, verbose_name='Lupin'),
        ),
        migrations.AddField(
            model_name='menu',
            name='milk',
            field=models.BooleanField(default=False, verbose_name='Milk'),
        ),
        migrations.AddField(
            model_name='menu',
            name='molluscs',
            field=models.BooleanField(default=False, verbose_name='Molluscs'),
        ),
        migrations.AddField(
            model_name='menu',
            name='mustard',
            field=models.BooleanField(default=False, verbose_name='Mustard'),
        ),
        migrations.AddField(
            model_name='menu',
            name='nuts',
            field=models.BooleanField(default=False, verbose_name='Nuts'),
        ),
        migrations.AddField(
            model_name='menu',
            name='peanuts',
            field=models.BooleanField(default=False, verbose_name='Peanuts'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sesame',
            field=models.BooleanField(default=False, verbose_name='Sesame'),
        ),
        migrations.AddField(
            model_name='menu',
            name='soybeans',
            field=models.BooleanField(default=False, verbose_name='Soybeans'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sulphur_dioxide',
            field=models.BooleanField(default=False, verbose_name='Sulphur Dioxide and Sulphites'),
        ),
        migrations.AddField(
            model_name='menu',
            name='wheat',
            field=models.BooleanField(default=False, verbose_name='Wheat'),
        ),
    ]
